# Generated by Django 4.1.5 on 2023-01-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="task", old_name="task", new_name="title",),
    ]
