# Generated by Django 4.1.5 on 2023-01-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0002_rename_task_task_title"),
    ]

    operations = [
        migrations.DeleteModel(name="Task",),
    ]
